<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\reena.pdf" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\reena.pdf" />
  </ItemGroup>

</Project>
